name: Build

on: [push]

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build
        run: xcodebuild
      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: bgpage
          path: dist
