name: Build snapshot

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build
        run: GITHUB_SHA=${{ github.sha }} xcodebuild
      - name: Create snapshot
        id: create_snapshot
        uses: actions/create-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: snapshot
          release_name: Snapshot
          draft: false
          prerelease: true
      - name: Upload snapshot asset
        uses: actions/upload-release-asset@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_snapshot.outputs.upload_url }}
          asset_path: ./bgpage-${{ github.sha }}.zip
          asset_name: bgpage-${{ github.sha }}.zip
          asset_content_type: application/zip
